feat:add UI Table with pagination[UI Kit Table]
Yu4er/Cosmetic-App pull request #3
Opened 2023-09-05 09:16 UTC by Yu4er

Создание UI Kit таблицы и пагинации

2023-09-11 12:37 UTC, konevm requested changes
Есть замечания

2023-09-11 12:37 UTC, konevm commented on src/components/UI/Table/TableBody.tsx
> +const styles = {
Выглядит как то что уже можно удалить

2023-09-11 12:37 UTC, konevm commented on src/components/UI/Table/TableBody.tsx
> +        )}
Лучше убрать тернарник в этом случае - слишком громоздкая запись получается

2023-09-11 12:37 UTC, konevm commented on src/components/UI/Table/TableHead.tsx
> +  isChecked?: boolean | undefined;
???

2023-09-11 12:37 UTC, konevm commented on src/components/UI/Table/TableHead.tsx
> +  handleAllClick?: () => void | undefined;
??????

2023-09-11 12:37 UTC, konevm commented on src/components/UI/Table/components/Pagination/Pagination.tsx
> +import { SelectDraw } from "./SelectDraw";
Странное наименование. Я прочитал как ВыбратьРисование - это то что имелось ввиду?

2023-09-11 12:37 UTC, konevm commented on src/components/UI/Table/components/RowTable/RowTable.tsx
> +import { IProductData } from "../../../../../interfaces/mockInterfaces";
это тоже тип?

2023-09-11 12:37 UTC, konevm commented on src/components/UI/Table/components/TablePopUp/TablePopUp.tsx
> +  }
Выглядит странно.

2023-09-11 12:37 UTC, konevm commented on src/components/UI/Table/components/TablePopUp/TablePopUp.tsx
> +          </svg>
Кажется что стоит это вынести в отдельный файл

2023-09-11 12:37 UTC, konevm commented on src/components/UI/Table/components/TablePopUp/TablePopUp.tsx
> +              </svg>
Аналогично

2023-09-11 12:37 UTC, konevm commented on src/components/UI/Table/components/TbodyCheckbox/TbodyCheckbox.tsx
> +function stopProp(e: React.MouseEvent) {
Не стоит сокращать, да и лучше переименовать на что-то более корректное

2023-09-11 12:37 UTC, konevm commented on src/components/UI/Table/components/TbodyCheckbox/TbodyCheckbox.tsx
> +export function TbodyCheckbox({
Body по правилам - тоже с большой

2023-09-11 12:37 UTC, konevm commented on src/components/UI/Table/components/TheadCheckbox/TheadCheckbox.tsx
> +export function TheadCheckbox({
Head тоже с большой

2023-09-11 12:37 UTC, konevm commented on src/hooks/usePagination.tsx
> +  const [limitRows, setLimitRows] = useState(10);
1 и 10 лучше выделить в отдельные константы `INITIAL_PAGE = 1, INITIAL_LIMIT = 10`, тогда запись
 `const [pagination, setPagination] = useState(INITIAL_PAGE );` - становится более очевидной

2023-09-11 12:37 UTC, konevm commented on src/hooks/usePagination.tsx
> +    setPagination(1);
См предыдущий комментарий

2023-09-11 12:37 UTC, konevm commented on src/interfaces/mockInterfaces.ts
> +}
Такие вещи обычно выделяют в отдельный интерфейс типа
 ```
IVariations {
    id: string;
    code: string;
    value: string;
}
```

Затем `variations?: IVariations[]`

2023-09-11 12:37 UTC, konevm commented on src/interfaces/mockInterfaces.ts
> +}
Не могут они зависеть друг от друга(extends)? Выглядят похоже.

2023-09-12 06:38 UTC, Yu4er commented on src/components/UI/Table/TableBody.tsx
> +        )}
Но мне нужно чтобы эта запись отображалась именно внутри, вместо таблицы. Как тогда, будет лучше сделать?

2023-09-13 05:31 UTC, konevm approved these changes

2023-09-13 05:31 UTC, konevm commented on src/components/UI/Table/TableBody.tsx
> +    <div>
Может использовать фрагмент вместо div?

2023-09-13 11:24 UTC, merged